services:
  odoo:
    container_name: odoo
    image: odoo:17.0
    env_file: .env
    ports:
      - "8070:8069"
    volumes:
      - ./var/lib/odoo:/var/lib/odoo
      - ./etc/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - odoo-postgres
    networks:
      - odoo-network
  odoo-postgres:
    container_name: odoo-postgres
    image: postgres:16.1
    env_file: .env
    
    networks:
      - odoo-network
networks:
  odoo-network:
    driver: bridge